"""Authentication: local email/password plus Supabase-token acceptance."""

from __future__ import annotations

from datetime import UTC, datetime

from fastapi import APIRouter, status
from sqlalchemy import select

from yatraai.api.v1.deps import CurrentUser, DbSession, RateLimited, write_audit
from yatraai.core.errors import AuthenticationError, ConflictError
from yatraai.core.security import create_access_token, hash_password, verify_password
from yatraai.db.models import User
from yatraai.schemas.common import ServiceBanner
from yatraai.schemas.trip import LoginRequest, RegisterRequest, TokenResponse, UserOut
from yatraai.services.status import active_degradations, service_status_snapshot

router = APIRouter(prefix="/auth", tags=["auth"])


@router.post(
    "/register",
    response_model=TokenResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create an account",
)
def register(payload: RegisterRequest, session: DbSession, _rl: RateLimited) -> TokenResponse:
    existing = session.scalar(select(User).where(User.email == payload.email.lower()))
    if existing is not None:
        raise ConflictError("An account with this email already exists.", code="email_taken")

    user = User(
        email=payload.email.lower(),
        display_name=payload.display_name.strip(),
        password_hash=hash_password(payload.password),
        home_city=payload.home_city,
        last_login_at=datetime.now(UTC),
    )
    session.add(user)
    session.flush()
    write_audit(
        session, action="user.register", entity_type="user", entity_id=str(user.id), actor=user
    )
    session.commit()

    token, expires = create_access_token(user.id, email=user.email, is_admin=user.is_admin)
    return TokenResponse(access_token=token, expires_at=expires, user=UserOut.model_validate(user))


@router.post("/login", response_model=TokenResponse, summary="Sign in")
def login(payload: LoginRequest, session: DbSession, _rl: RateLimited) -> TokenResponse:
    user = session.scalar(select(User).where(User.email == payload.email.lower()))
    # Constant-ish work whether or not the account exists, so timing does not leak.
    if user is None or not verify_password(payload.password, user.password_hash):
        raise AuthenticationError("Incorrect email or password.")
    if not user.is_active:
        raise AuthenticationError("This account is disabled.")

    user.last_login_at = datetime.now(UTC)
    session.commit()

    token, expires = create_access_token(user.id, email=user.email, is_admin=user.is_admin)
    return TokenResponse(access_token=token, expires_at=expires, user=UserOut.model_validate(user))


@router.get("/me", response_model=UserOut, summary="Current user")
def me(user: CurrentUser) -> UserOut:
    return UserOut.model_validate(user)


@router.get(
    "/demo",
    response_model=TokenResponse,
    summary="Sign in as the read-only demo user",
    description=(
        "Creates (or reuses) a clearly-labelled demo account so a reviewer can explore the "
        "product without registering. Demo data is regenerated by `yatraai demo --reset`."
    ),
)
def demo_login(session: DbSession, _rl: RateLimited) -> TokenResponse:
    from yatraai.services.demo import ensure_demo_data

    info = ensure_demo_data(session)
    session.commit()
    user = session.get(User, info["user_id"])
    if user is None:  # pragma: no cover - ensure_demo_data always creates one
        raise AuthenticationError("Demo account unavailable.")
    token, expires = create_access_token(user.id, email=user.email, is_admin=user.is_admin)
    return TokenResponse(access_token=token, expires_at=expires, user=UserOut.model_validate(user))


@router.get(
    "/service-status",
    response_model=ServiceBanner,
    tags=["ops"],
    summary="Which providers are live vs degraded",
)
def service_status() -> ServiceBanner:
    messages = active_degradations()
    return ServiceBanner(
        degraded=bool(messages), messages=messages, providers=service_status_snapshot()
    )
