"""Destination catalogue: clusters, attractions, schedules, costs, sources.

This is the *fact layer*. Nothing here is ever generated by an LLM; every row
originates from the curated seed dataset or the Bronze->Silver->Gold pipeline and
carries provenance (`attraction_sources`) plus a verification timestamp.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from yatraai.db.base import (
    GUID,
    Base,
    JSONType,
    TimestampMixin,
    TZDateTime,
    UUIDPrimaryKeyMixin,
)


class DestinationCluster(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """A curated travel region (e.g. ``delhi-agra``)."""

    __tablename__ = "destination_clusters"

    slug: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)
    name: Mapped[str] = mapped_column(String(160), nullable=False)
    state: Mapped[str] = mapped_column(String(80), nullable=False)
    region: Mapped[str] = mapped_column(String(40), nullable=False)  # north/south/east/...
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    travel_style: Mapped[list] = mapped_column(JSONType, default=list, nullable=False)
    center_lat: Mapped[float] = mapped_column(Float, nullable=False)
    center_lon: Mapped[float] = mapped_column(Float, nullable=False)
    timezone: Mapped[str] = mapped_column(String(48), default="Asia/Kolkata", nullable=False)
    best_months: Mapped[list] = mapped_column(JSONType, default=list, nullable=False)
    avoid_months: Mapped[list] = mapped_column(JSONType, default=list, nullable=False)
    recommended_days: Mapped[int] = mapped_column(Integer, default=3, nullable=False)
    # Baseline per-person per-day costs in INR used by the cost estimator.
    daily_cost_baseline: Mapped[dict] = mapped_column(JSONType, default=dict, nullable=False)
    intercity_hub: Mapped[str | None] = mapped_column(String(120))
    hero_image_url: Mapped[str | None] = mapped_column(Text)
    image_attribution: Mapped[str | None] = mapped_column(Text)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    attractions: Mapped[list[Attraction]] = relationship(
        back_populates="cluster", cascade="all, delete-orphan"
    )

    __table_args__ = (
        CheckConstraint("center_lat BETWEEN -90 AND 90", name="cluster_lat_range"),
        CheckConstraint("center_lon BETWEEN -180 AND 180", name="cluster_lon_range"),
    )


class Attraction(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "attractions"

    cluster_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("destination_clusters.id", ondelete="CASCADE"), nullable=False
    )
    slug: Mapped[str] = mapped_column(String(96), nullable=False, index=True)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    locality: Mapped[str] = mapped_column(String(160), nullable=False)
    city: Mapped[str] = mapped_column(String(120), nullable=False)
    lat: Mapped[float] = mapped_column(Float, nullable=False)
    lon: Mapped[float] = mapped_column(Float, nullable=False)

    categories: Mapped[list] = mapped_column(JSONType, default=list, nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    history: Mapped[str] = mapped_column(Text, nullable=False, default="")
    significance: Mapped[str] = mapped_column(Text, nullable=False, default="")
    interesting_facts: Mapped[list] = mapped_column(JSONType, default=list, nullable=False)

    # --- planning inputs -----------------------------------------------------
    typical_duration_min: Mapped[int] = mapped_column(Integer, nullable=False, default=60)
    min_duration_min: Mapped[int] = mapped_column(Integer, nullable=False, default=30)
    max_duration_min: Mapped[int] = mapped_column(Integer, nullable=False, default=180)
    best_time_of_day: Mapped[list] = mapped_column(JSONType, default=list, nullable=False)
    suitable_months: Mapped[list] = mapped_column(JSONType, default=list, nullable=False)
    indoor_outdoor: Mapped[str] = mapped_column(String(16), default="outdoor", nullable=False)
    weather_sensitivity: Mapped[float] = mapped_column(Float, default=0.5, nullable=False)
    typical_crowd_level: Mapped[str] = mapped_column(String(16), default="medium", nullable=False)
    crowd_by_time: Mapped[dict] = mapped_column(JSONType, default=dict, nullable=False)

    # --- suitability ---------------------------------------------------------
    wheelchair_accessible: Mapped[str] = mapped_column(
        String(16), default="unknown", nullable=False
    )  # yes | partial | no | unknown
    accessibility_notes: Mapped[str] = mapped_column(Text, default="", nullable=False)
    senior_friendly: Mapped[int] = mapped_column(Integer, default=3, nullable=False)  # 1-5
    child_friendly: Mapped[int] = mapped_column(Integer, default=3, nullable=False)  # 1-5
    physical_intensity: Mapped[int] = mapped_column(Integer, default=2, nullable=False)  # 1-5

    # --- etiquette -----------------------------------------------------------
    dress_code: Mapped[str] = mapped_column(Text, default="", nullable=False)
    photography_policy: Mapped[str] = mapped_column(Text, default="", nullable=False)
    local_customs: Mapped[list] = mapped_column(JSONType, default=list, nullable=False)

    # --- quality / verification ---------------------------------------------
    quality_score: Mapped[float] = mapped_column(Float, default=0.6, nullable=False)
    popularity_rank: Mapped[int] = mapped_column(Integer, default=50, nullable=False)
    nearby_attraction_slugs: Mapped[list] = mapped_column(JSONType, default=list, nullable=False)
    hero_image_url: Mapped[str | None] = mapped_column(Text)
    image_attribution: Mapped[str | None] = mapped_column(Text)
    data_confidence: Mapped[str] = mapped_column(String(16), default="medium", nullable=False)
    needs_verification: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    verification_note: Mapped[str] = mapped_column(Text, default="", nullable=False)
    last_verified_at: Mapped[date | None] = mapped_column(Date)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    cluster: Mapped[DestinationCluster] = relationship(back_populates="attractions")
    schedules: Mapped[list[AttractionSchedule]] = relationship(
        back_populates="attraction", cascade="all, delete-orphan"
    )
    costs: Mapped[list[AttractionCost]] = relationship(
        back_populates="attraction", cascade="all, delete-orphan"
    )
    sources: Mapped[list[AttractionSource]] = relationship(
        back_populates="attraction", cascade="all, delete-orphan"
    )

    __table_args__ = (
        UniqueConstraint("cluster_id", "slug", name="uq_attraction_cluster_slug"),
        CheckConstraint("lat BETWEEN -90 AND 90", name="attraction_lat_range"),
        CheckConstraint("lon BETWEEN -180 AND 180", name="attraction_lon_range"),
        CheckConstraint("typical_duration_min > 0", name="attraction_duration_positive"),
        CheckConstraint("senior_friendly BETWEEN 1 AND 5", name="attraction_senior_range"),
        CheckConstraint("child_friendly BETWEEN 1 AND 5", name="attraction_child_range"),
        Index("ix_attractions_cluster_active", "cluster_id", "is_active"),
        Index("ix_attractions_geo", "lat", "lon"),
    )


class AttractionSchedule(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Opening hours. ``day_of_week`` 0=Monday .. 6=Sunday, -1 = all days."""

    __tablename__ = "attraction_schedules"

    attraction_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("attractions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    day_of_week: Mapped[int] = mapped_column(Integer, nullable=False)
    opens_min: Mapped[int | None] = mapped_column(Integer)  # minutes from midnight
    closes_min: Mapped[int | None] = mapped_column(Integer)
    is_closed: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    season: Mapped[str] = mapped_column(String(24), default="all", nullable=False)
    note: Mapped[str] = mapped_column(Text, default="", nullable=False)
    verified: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    attraction: Mapped[Attraction] = relationship(back_populates="schedules")

    __table_args__ = (
        CheckConstraint("day_of_week BETWEEN -1 AND 6", name="schedule_dow_range"),
        CheckConstraint(
            "opens_min IS NULL OR (opens_min >= 0 AND opens_min <= 1440)",
            name="schedule_opens_range",
        ),
        CheckConstraint(
            "closes_min IS NULL OR (closes_min >= 0 AND closes_min <= 1560)",
            name="schedule_closes_range",
        ),
    )


class AttractionCost(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Entry fees. Ranges are stored explicitly - we never fake precision."""

    __tablename__ = "attraction_costs"

    attraction_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("attractions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    visitor_type: Mapped[str] = mapped_column(
        String(32), default="indian_adult", nullable=False
    )  # indian_adult | foreign_adult | child | senior | camera | parking
    currency: Mapped[str] = mapped_column(String(8), default="INR", nullable=False)
    amount_min: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    amount_max: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    is_free: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    note: Mapped[str] = mapped_column(Text, default="", nullable=False)
    verified: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    attraction: Mapped[Attraction] = relationship(back_populates="costs")

    __table_args__ = (
        CheckConstraint("amount_min >= 0 AND amount_max >= amount_min", name="cost_range_valid"),
    )


class AttractionSource(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Provenance for a specific attraction field group."""

    __tablename__ = "attraction_sources"

    attraction_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("attractions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    url: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str] = mapped_column(Text, default="", nullable=False)
    source_type: Mapped[str] = mapped_column(
        String(32), default="official", nullable=False
    )  # official | government | encyclopedic | openstreetmap | editorial
    covers_fields: Mapped[list] = mapped_column(JSONType, default=list, nullable=False)
    retrieved_at: Mapped[datetime | None] = mapped_column(TZDateTime)
    last_verified_at: Mapped[date | None] = mapped_column(Date)

    attraction: Mapped[Attraction] = relationship(back_populates="sources")
