"""initial schema

Revision ID: ea4563174965
Revises:
Create Date: 2026-08-03 02:02:00.782034
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import yatraai.db.base

revision: str = "ea4563174965"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_events",
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("trip_id", yatraai.db.base.GUID(length=36), nullable=True),
        sa.Column("cluster_slug", sa.String(length=64), nullable=True),
        sa.Column("user_id", yatraai.db.base.GUID(length=36), nullable=True),
        sa.Column("numeric_value", sa.Float(), nullable=True),
        sa.Column("properties", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_events")),
    )
    with op.batch_alter_table("analytics_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analytics_events_cluster_slug"), ["cluster_slug"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_analytics_events_event"), ["event"], unique=False)
        batch_op.create_index(batch_op.f("ix_analytics_events_trip_id"), ["trip_id"], unique=False)

    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", yatraai.db.base.GUID(length=36), nullable=True),
        sa.Column("actor_label", sa.String(length=160), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=48), nullable=False),
        sa.Column("entity_id", sa.String(length=96), nullable=True),
        sa.Column("trip_id", yatraai.db.base.GUID(length=36), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("detail", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index("ix_audit_action_created", ["action", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_trip_id"), ["trip_id"], unique=False)

    op.create_table(
        "destination_clusters",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("state", sa.String(length=80), nullable=False),
        sa.Column("region", sa.String(length=40), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("travel_style", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("center_lat", sa.Float(), nullable=False),
        sa.Column("center_lon", sa.Float(), nullable=False),
        sa.Column("timezone", sa.String(length=48), nullable=False),
        sa.Column("best_months", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("avoid_months", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("recommended_days", sa.Integer(), nullable=False),
        sa.Column("daily_cost_baseline", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("intercity_hub", sa.String(length=120), nullable=True),
        sa.Column("hero_image_url", sa.Text(), nullable=True),
        sa.Column("image_attribution", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "center_lat BETWEEN -90 AND 90", name=op.f("ck_destination_clusters_cluster_lat_range")
        ),
        sa.CheckConstraint(
            "center_lon BETWEEN -180 AND 180",
            name=op.f("ck_destination_clusters_cluster_lon_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_destination_clusters")),
    )
    with op.batch_alter_table("destination_clusters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_destination_clusters_slug"), ["slug"], unique=True)

    op.create_table(
        "model_runs",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("experiment", sa.String(length=96), nullable=False),
        sa.Column("model_name", sa.String(length=96), nullable=False),
        sa.Column("data_kind", sa.String(length=24), nullable=False),
        sa.Column("params", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("metrics", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("dataset_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_runs")),
    )
    with op.batch_alter_table("model_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_model_runs_run_id"), ["run_id"], unique=True)

    op.create_table(
        "pipeline_runs",
        sa.Column("pipeline", sa.String(length=64), nullable=False),
        sa.Column("layer", sa.String(length=16), nullable=False),
        sa.Column("run_key", sa.String(length=96), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("rows_in", sa.Integer(), nullable=False),
        sa.Column("rows_out", sa.Integer(), nullable=False),
        sa.Column("rows_rejected", sa.Integer(), nullable=False),
        sa.Column("started_at", yatraai.db.base.TZDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", yatraai.db.base.TZDateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("checks", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_runs")),
        sa.UniqueConstraint("pipeline", "run_key", name="uq_pipeline_run_key"),
    )
    with op.batch_alter_table("pipeline_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pipeline_runs_pipeline"), ["pipeline"], unique=False)

    op.create_table(
        "rag_evaluations",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("question_id", sa.String(length=64), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("cluster_slug", sa.String(length=64), nullable=True),
        sa.Column("attraction_slug", sa.String(length=96), nullable=True),
        sa.Column("retrieval_precision", sa.Float(), nullable=False),
        sa.Column("retrieval_recall", sa.Float(), nullable=False),
        sa.Column("context_relevance", sa.Float(), nullable=False),
        sa.Column("faithfulness", sa.Float(), nullable=False),
        sa.Column("citation_correctness", sa.Float(), nullable=False),
        sa.Column("answer_completeness", sa.Float(), nullable=False),
        sa.Column("abstained", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("retrieved_chunk_ids", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("meta", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rag_evaluations")),
    )
    with op.batch_alter_table("rag_evaluations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rag_evaluations_run_id"), ["run_id"], unique=False)

    op.create_table(
        "route_cache",
        sa.Column("cache_key", sa.String(length=128), nullable=False),
        sa.Column("origin_lat", sa.Float(), nullable=False),
        sa.Column("origin_lon", sa.Float(), nullable=False),
        sa.Column("dest_lat", sa.Float(), nullable=False),
        sa.Column("dest_lon", sa.Float(), nullable=False),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("provider", sa.String(length=24), nullable=False),
        sa.Column("distance_km", sa.Float(), nullable=False),
        sa.Column("duration_min", sa.Float(), nullable=False),
        sa.Column("is_fallback", sa.Boolean(), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_cache")),
    )
    with op.batch_alter_table("route_cache", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_route_cache_cache_key"), ["cache_key"], unique=True)

    op.create_table(
        "service_call_logs",
        sa.Column("service", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("fallback_used", sa.Boolean(), nullable=False),
        sa.Column("error_kind", sa.String(length=64), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_call_logs")),
    )
    with op.batch_alter_table("service_call_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_service_call_logs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_service_call_logs_service"), ["service"], unique=False)
        batch_op.create_index("ix_svc_service_created", ["service", "created_at"], unique=False)

    op.create_table(
        "source_documents",
        sa.Column("doc_key", sa.String(length=160), nullable=False),
        sa.Column("cluster_slug", sa.String(length=64), nullable=False),
        sa.Column("attraction_slug", sa.String(length=96), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("content_category", sa.String(length=40), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_title", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("retrieved_at", yatraai.db.base.TZDateTime(timezone=True), nullable=True),
        sa.Column("last_verified_at", sa.Date(), nullable=True),
        sa.Column("time_sensitive", sa.Boolean(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
    )
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_documents_attraction_slug"), ["attraction_slug"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_source_documents_cluster_slug"), ["cluster_slug"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_source_documents_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_source_documents_doc_key"), ["doc_key"], unique=True)
        batch_op.create_index(
            "ix_srcdoc_cluster_attr", ["cluster_slug", "attraction_slug"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("supabase_user_id", sa.String(length=64), nullable=True),
        sa.Column("avatar_seed", sa.String(length=32), nullable=False),
        sa.Column("home_city", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("default_preferences", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("last_login_at", yatraai.db.base.TZDateTime(timezone=True), nullable=True),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("supabase_user_id", name=op.f("uq_users_supabase_user_id")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "weather_snapshots",
        sa.Column("cluster_slug", sa.String(length=64), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("temp_min_c", sa.Float(), nullable=True),
        sa.Column("temp_max_c", sa.Float(), nullable=True),
        sa.Column("precipitation_mm", sa.Float(), nullable=True),
        sa.Column("precipitation_probability", sa.Float(), nullable=True),
        sa.Column("wind_kph", sa.Float(), nullable=True),
        sa.Column("visibility_km", sa.Float(), nullable=True),
        sa.Column("weather_code", sa.Integer(), nullable=True),
        sa.Column("condition", sa.String(length=40), nullable=False),
        sa.Column("is_fallback", sa.Boolean(), nullable=False),
        sa.Column("raw", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("fetched_at", yatraai.db.base.TZDateTime(timezone=True), nullable=True),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_snapshots")),
        sa.UniqueConstraint(
            "cluster_slug", "target_date", "provider", name="uq_weather_cluster_date_provider"
        ),
    )
    with op.batch_alter_table("weather_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_weather_snapshots_cluster_slug"), ["cluster_slug"], unique=False
        )

    op.create_table(
        "attractions",
        sa.Column("cluster_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("slug", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("locality", sa.String(length=160), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("categories", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("history", sa.Text(), nullable=False),
        sa.Column("significance", sa.Text(), nullable=False),
        sa.Column("interesting_facts", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("typical_duration_min", sa.Integer(), nullable=False),
        sa.Column("min_duration_min", sa.Integer(), nullable=False),
        sa.Column("max_duration_min", sa.Integer(), nullable=False),
        sa.Column("best_time_of_day", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("suitable_months", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("indoor_outdoor", sa.String(length=16), nullable=False),
        sa.Column("weather_sensitivity", sa.Float(), nullable=False),
        sa.Column("typical_crowd_level", sa.String(length=16), nullable=False),
        sa.Column("crowd_by_time", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("wheelchair_accessible", sa.String(length=16), nullable=False),
        sa.Column("accessibility_notes", sa.Text(), nullable=False),
        sa.Column("senior_friendly", sa.Integer(), nullable=False),
        sa.Column("child_friendly", sa.Integer(), nullable=False),
        sa.Column("physical_intensity", sa.Integer(), nullable=False),
        sa.Column("dress_code", sa.Text(), nullable=False),
        sa.Column("photography_policy", sa.Text(), nullable=False),
        sa.Column("local_customs", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("popularity_rank", sa.Integer(), nullable=False),
        sa.Column("nearby_attraction_slugs", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("hero_image_url", sa.Text(), nullable=True),
        sa.Column("image_attribution", sa.Text(), nullable=True),
        sa.Column("data_confidence", sa.String(length=16), nullable=False),
        sa.Column("needs_verification", sa.Boolean(), nullable=False),
        sa.Column("verification_note", sa.Text(), nullable=False),
        sa.Column("last_verified_at", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "child_friendly BETWEEN 1 AND 5", name=op.f("ck_attractions_attraction_child_range")
        ),
        sa.CheckConstraint(
            "lat BETWEEN -90 AND 90", name=op.f("ck_attractions_attraction_lat_range")
        ),
        sa.CheckConstraint(
            "lon BETWEEN -180 AND 180", name=op.f("ck_attractions_attraction_lon_range")
        ),
        sa.CheckConstraint(
            "senior_friendly BETWEEN 1 AND 5", name=op.f("ck_attractions_attraction_senior_range")
        ),
        sa.CheckConstraint(
            "typical_duration_min > 0", name=op.f("ck_attractions_attraction_duration_positive")
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["destination_clusters.id"],
            name=op.f("fk_attractions_cluster_id_destination_clusters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attractions")),
        sa.UniqueConstraint("cluster_id", "slug", name="uq_attraction_cluster_slug"),
    )
    with op.batch_alter_table("attractions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_attractions_cluster_active", ["cluster_id", "is_active"], unique=False
        )
        batch_op.create_index("ix_attractions_geo", ["lat", "lon"], unique=False)
        batch_op.create_index(batch_op.f("ix_attractions_slug"), ["slug"], unique=False)

    op.create_table(
        "document_chunks",
        sa.Column("document_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("heading", sa.String(length=240), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_estimate", sa.Integer(), nullable=False),
        sa.Column("cluster_slug", sa.String(length=64), nullable=False),
        sa.Column("attraction_slug", sa.String(length=96), nullable=True),
        sa.Column("content_category", sa.String(length=40), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("last_verified_at", sa.Date(), nullable=True),
        sa.Column("keywords", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["source_documents.id"],
            name=op.f("fk_document_chunks_document_id_source_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_chunk_doc_index"),
    )
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.create_index("ix_chunk_filter", ["cluster_slug", "content_category"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_document_chunks_attraction_slug"), ["attraction_slug"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_chunks_cluster_slug"), ["cluster_slug"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_chunks_content_category"), ["content_category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_chunks_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_chunks_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "trips",
        sa.Column("owner_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("cluster_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("origin_label", sa.String(length=160), nullable=False),
        sa.Column("origin_lat", sa.Float(), nullable=True),
        sa.Column("origin_lon", sa.Float(), nullable=True),
        sa.Column("traveller_count", sa.Integer(), nullable=False),
        sa.Column("budget_total_inr", sa.Float(), nullable=True),
        sa.Column("budget_per_person_inr", sa.Float(), nullable=True),
        sa.Column("budget_basis", sa.String(length=16), nullable=False),
        sa.Column("pace", sa.String(length=16), nullable=False),
        sa.Column("transport_mode", sa.String(length=24), nullable=False),
        sa.Column("accommodation_tier", sa.String(length=24), nullable=False),
        sa.Column("day_start_min", sa.Integer(), nullable=False),
        sa.Column("day_end_min", sa.Integer(), nullable=False),
        sa.Column("has_children", sa.Boolean(), nullable=False),
        sa.Column("has_seniors", sa.Boolean(), nullable=False),
        sa.Column("accessibility_required", sa.Boolean(), nullable=False),
        sa.Column("must_visit_slugs", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("avoid_slugs", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("invite_code", sa.String(length=12), nullable=False),
        sa.Column("invite_enabled", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.CheckConstraint("day_end_min > day_start_min", name=op.f("ck_trips_trip_day_window")),
        sa.CheckConstraint("end_date >= start_date", name=op.f("ck_trips_trip_date_order")),
        sa.CheckConstraint("traveller_count >= 1", name=op.f("ck_trips_trip_traveller_min")),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["destination_clusters.id"],
            name=op.f("fk_trips_cluster_id_destination_clusters"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_trips_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trips")),
    )
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trips_cluster_id"), ["cluster_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_trips_invite_code"), ["invite_code"], unique=True)
        batch_op.create_index(batch_op.f("ix_trips_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index("ix_trips_owner_status", ["owner_id", "status"], unique=False)

    op.create_table(
        "attraction_costs",
        sa.Column("attraction_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("visitor_type", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("amount_min", sa.Float(), nullable=False),
        sa.Column("amount_max", sa.Float(), nullable=False),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "amount_min >= 0 AND amount_max >= amount_min",
            name=op.f("ck_attraction_costs_cost_range_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["attraction_id"],
            ["attractions.id"],
            name=op.f("fk_attraction_costs_attraction_id_attractions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attraction_costs")),
    )
    with op.batch_alter_table("attraction_costs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attraction_costs_attraction_id"), ["attraction_id"], unique=False
        )

    op.create_table(
        "attraction_schedules",
        sa.Column("attraction_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("opens_min", sa.Integer(), nullable=True),
        sa.Column("closes_min", sa.Integer(), nullable=True),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("season", sa.String(length=24), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "closes_min IS NULL OR (closes_min >= 0 AND closes_min <= 1560)",
            name=op.f("ck_attraction_schedules_schedule_closes_range"),
        ),
        sa.CheckConstraint(
            "day_of_week BETWEEN -1 AND 6", name=op.f("ck_attraction_schedules_schedule_dow_range")
        ),
        sa.CheckConstraint(
            "opens_min IS NULL OR (opens_min >= 0 AND opens_min <= 1440)",
            name=op.f("ck_attraction_schedules_schedule_opens_range"),
        ),
        sa.ForeignKeyConstraint(
            ["attraction_id"],
            ["attractions.id"],
            name=op.f("fk_attraction_schedules_attraction_id_attractions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attraction_schedules")),
    )
    with op.batch_alter_table("attraction_schedules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attraction_schedules_attraction_id"), ["attraction_id"], unique=False
        )

    op.create_table(
        "attraction_sources",
        sa.Column("attraction_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("covers_fields", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("retrieved_at", yatraai.db.base.TZDateTime(timezone=True), nullable=True),
        sa.Column("last_verified_at", sa.Date(), nullable=True),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attraction_id"],
            ["attractions.id"],
            name=op.f("fk_attraction_sources_attraction_id_attractions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attraction_sources")),
    )
    with op.batch_alter_table("attraction_sources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attraction_sources_attraction_id"), ["attraction_id"], unique=False
        )

    op.create_table(
        "chunk_embeddings",
        sa.Column("chunk_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("vector", yatraai.db.base.VectorType(dim=384), nullable=False),
        sa.Column("norm", sa.Float(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_chunk_embeddings_chunk_id_document_chunks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunk_embeddings")),
        sa.UniqueConstraint("chunk_id", name=op.f("uq_chunk_embeddings_chunk_id")),
    )
    op.create_table(
        "itineraries",
        sa.Column("trip_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_itinerary_id", yatraai.db.base.GUID(length=36), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("generator", sa.String(length=24), nullable=False),
        sa.Column("trigger", sa.String(length=40), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("validation_report", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("total_travel_km", sa.Float(), nullable=False),
        sa.Column("total_travel_min", sa.Integer(), nullable=False),
        sa.Column("total_visit_min", sa.Integer(), nullable=False),
        sa.Column("activity_count", sa.Integer(), nullable=False),
        sa.Column("fairness_score", sa.Float(), nullable=False),
        sa.Column("least_satisfied_score", sa.Float(), nullable=False),
        sa.Column("consensus_score", sa.Float(), nullable=False),
        sa.Column("utility_score", sa.Float(), nullable=False),
        sa.Column("preference_coverage", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("cost_low_inr", sa.Float(), nullable=False),
        sa.Column("cost_high_inr", sa.Float(), nullable=False),
        sa.Column("cost_per_person_low_inr", sa.Float(), nullable=False),
        sa.Column("cost_per_person_high_inr", sa.Float(), nullable=False),
        sa.Column("cost_breakdown", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("explanation_source", sa.String(length=24), nullable=False),
        sa.Column("llm_provider", sa.String(length=24), nullable=True),
        sa.Column("degraded_services", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("solver_stats", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_itineraries_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_itineraries")),
        sa.UniqueConstraint("trip_id", "version", name="uq_itinerary_trip_version"),
    )
    with op.batch_alter_table("itineraries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_itineraries_trip_id"), ["trip_id"], unique=False)
        batch_op.create_index("ix_itineraries_trip_status", ["trip_id", "status"], unique=False)

    op.create_table(
        "trip_members",
        sa.Column("trip_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("user_id", yatraai.db.base.GUID(length=36), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("joined_at", yatraai.db.base.TZDateTime(timezone=True), nullable=True),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.CheckConstraint("weight > 0", name=op.f("ck_trip_members_member_weight_positive")),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_trip_members_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_trip_members_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trip_members")),
        sa.UniqueConstraint("trip_id", "user_id", name="uq_trip_member_user"),
    )
    with op.batch_alter_table("trip_members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trip_members_trip_id"), ["trip_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_trip_members_user_id"), ["user_id"], unique=False)

    op.create_table(
        "change_proposals",
        sa.Column("trip_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("itinerary_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("proposed_by_member_id", yatraai.db.base.GUID(length=36), nullable=True),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("payload", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("diff", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("candidate_itinerary_id", yatraai.db.base.GUID(length=36), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("required_approvals", sa.Integer(), nullable=False),
        sa.Column("resolved_at", yatraai.db.base.TZDateTime(timezone=True), nullable=True),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
            name=op.f("fk_change_proposals_itinerary_id_itineraries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_member_id"],
            ["trip_members.id"],
            name=op.f("fk_change_proposals_proposed_by_member_id_trip_members"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_change_proposals_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_proposals")),
    )
    with op.batch_alter_table("change_proposals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_change_proposals_trip_id"), ["trip_id"], unique=False)

    op.create_table(
        "chat_messages",
        sa.Column("trip_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("member_id", yatraai.db.base.GUID(length=36), nullable=True),
        sa.Column("author_name", sa.String(length=120), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("meta", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["trip_members.id"],
            name=op.f("fk_chat_messages_member_id_trip_members"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_chat_messages_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chat_messages_trip_id"), ["trip_id"], unique=False)
        batch_op.create_index("ix_chat_trip_created", ["trip_id", "created_at"], unique=False)

    op.create_table(
        "feedback",
        sa.Column("trip_id", yatraai.db.base.GUID(length=36), nullable=True),
        sa.Column("itinerary_id", yatraai.db.base.GUID(length=36), nullable=True),
        sa.Column("user_id", yatraai.db.base.GUID(length=36), nullable=True),
        sa.Column("subject_type", sa.String(length=24), nullable=False),
        sa.Column("subject_id", sa.String(length=96), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("accepted", sa.Boolean(), nullable=True),
        sa.Column("actual_spend_inr", sa.Float(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("meta", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "rating IS NULL OR rating BETWEEN 1 AND 5", name=op.f("ck_feedback_fb_rating")
        ),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
            name=op.f("fk_feedback_itinerary_id_itineraries"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_feedback_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_feedback_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
    )
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feedback_trip_id"), ["trip_id"], unique=False)

    op.create_table(
        "itinerary_days",
        sa.Column("itinerary_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("day_index", sa.Integer(), nullable=False),
        sa.Column("calendar_date", sa.Date(), nullable=False),
        sa.Column("start_min", sa.Integer(), nullable=False),
        sa.Column("end_min", sa.Integer(), nullable=False),
        sa.Column("base_lat", sa.Float(), nullable=False),
        sa.Column("base_lon", sa.Float(), nullable=False),
        sa.Column("travel_km", sa.Float(), nullable=False),
        sa.Column("travel_min", sa.Integer(), nullable=False),
        sa.Column("weather", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("weather_advisories", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("theme", sa.String(length=80), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
            name=op.f("fk_itinerary_days_itinerary_id_itineraries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_itinerary_days")),
        sa.UniqueConstraint("itinerary_id", "day_index", name="uq_day_itinerary_index"),
    )
    with op.batch_alter_table("itinerary_days", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_itinerary_days_itinerary_id"), ["itinerary_id"], unique=False
        )

    op.create_table(
        "location_sharing_sessions",
        sa.Column("trip_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("member_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("precision", sa.String(length=16), nullable=False),
        sa.Column("update_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("consent_granted_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("consent_text_version", sa.String(length=24), nullable=False),
        sa.Column("expires_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("stopped_at", yatraai.db.base.TZDateTime(timezone=True), nullable=True),
        sa.Column("last_point_at", yatraai.db.base.TZDateTime(timezone=True), nullable=True),
        sa.Column("share_with", sa.String(length=16), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "update_interval_seconds >= 15",
            name=op.f("ck_location_sharing_sessions_loc_interval_min"),
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["trip_members.id"],
            name=op.f("fk_location_sharing_sessions_member_id_trip_members"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_location_sharing_sessions_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_location_sharing_sessions")),
    )
    with op.batch_alter_table("location_sharing_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_location_sharing_sessions_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_location_sharing_sessions_member_id"), ["member_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_location_sharing_sessions_trip_id"), ["trip_id"], unique=False
        )
        batch_op.create_index("ix_locsession_trip_status", ["trip_id", "status"], unique=False)

    op.create_table(
        "member_preferences",
        sa.Column("member_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("trip_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("interests", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("ranked_choices", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("pace", sa.String(length=16), nullable=False),
        sa.Column("budget_sensitivity", sa.Integer(), nullable=False),
        sa.Column("indoor_outdoor_pref", sa.String(length=16), nullable=False),
        sa.Column("dietary", sa.String(length=24), nullable=False),
        sa.Column("mobility_level", sa.String(length=24), nullable=False),
        sa.Column("max_walk_minutes", sa.Integer(), nullable=False),
        sa.Column("earliest_start_min", sa.Integer(), nullable=False),
        sa.Column("latest_end_min", sa.Integer(), nullable=False),
        sa.Column("must_visit_slugs", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("avoid_slugs", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("submitted", sa.Boolean(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "budget_sensitivity BETWEEN 1 AND 5",
            name=op.f("ck_member_preferences_pref_budget_sens_range"),
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["trip_members.id"],
            name=op.f("fk_member_preferences_member_id_trip_members"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_member_preferences_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_member_preferences")),
        sa.UniqueConstraint("member_id", name=op.f("uq_member_preferences_member_id")),
    )
    with op.batch_alter_table("member_preferences", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_member_preferences_trip_id"), ["trip_id"], unique=False
        )

    op.create_table(
        "recommendation_scores",
        sa.Column("trip_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("itinerary_id", yatraai.db.base.GUID(length=36), nullable=True),
        sa.Column("attraction_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("attraction_slug", sa.String(length=96), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("components", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("per_member_scores", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("eligibility", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attraction_id"],
            ["attractions.id"],
            name=op.f("fk_recommendation_scores_attraction_id_attractions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
            name=op.f("fk_recommendation_scores_itinerary_id_itineraries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_recommendation_scores_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_scores")),
    )
    with op.batch_alter_table("recommendation_scores", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recommendation_scores_trip_id"), ["trip_id"], unique=False
        )
        batch_op.create_index("ix_recscore_trip_rank", ["trip_id", "rank"], unique=False)

    op.create_table(
        "sos_alerts",
        sa.Column("trip_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("member_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("approx_lat", sa.Float(), nullable=True),
        sa.Column("approx_lon", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("meta", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["trip_members.id"],
            name=op.f("fk_sos_alerts_member_id_trip_members"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_sos_alerts_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sos_alerts")),
    )
    with op.batch_alter_table("sos_alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sos_alerts_trip_id"), ["trip_id"], unique=False)

    op.create_table(
        "votes",
        sa.Column("trip_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("member_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("subject_type", sa.String(length=24), nullable=False),
        sa.Column("subject_id", sa.String(length=96), nullable=False),
        sa.Column("value", sa.String(length=16), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["trip_members.id"],
            name=op.f("fk_votes_member_id_trip_members"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_votes_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_votes")),
        sa.UniqueConstraint(
            "member_id", "subject_type", "subject_id", name="uq_vote_member_subject"
        ),
    )
    with op.batch_alter_table("votes", schema=None) as batch_op:
        batch_op.create_index("ix_votes_subject", ["subject_type", "subject_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_votes_trip_id"), ["trip_id"], unique=False)

    op.create_table(
        "itinerary_activities",
        sa.Column("day_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("attraction_id", yatraai.db.base.GUID(length=36), nullable=True),
        sa.Column("attraction_slug", sa.String(length=96), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("start_min", sa.Integer(), nullable=False),
        sa.Column("end_min", sa.Integer(), nullable=False),
        sa.Column("travel_from_prev_min", sa.Integer(), nullable=False),
        sa.Column("travel_from_prev_km", sa.Float(), nullable=False),
        sa.Column("travel_mode", sa.String(length=24), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("est_cost_low_inr", sa.Float(), nullable=False),
        sa.Column("est_cost_high_inr", sa.Float(), nullable=False),
        sa.Column("weather_suitability", sa.Float(), nullable=False),
        sa.Column("warnings", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("why_selected", sa.Text(), nullable=False),
        sa.Column("score_breakdown", yatraai.db.base.JSONType(), nullable=False),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "end_min > start_min", name=op.f("ck_itinerary_activities_activity_time_order")
        ),
        sa.ForeignKeyConstraint(
            ["attraction_id"],
            ["attractions.id"],
            name=op.f("fk_itinerary_activities_attraction_id_attractions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["day_id"],
            ["itinerary_days.id"],
            name=op.f("fk_itinerary_activities_day_id_itinerary_days"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_itinerary_activities")),
        sa.UniqueConstraint("day_id", "sequence", name="uq_activity_day_sequence"),
    )
    with op.batch_alter_table("itinerary_activities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_itinerary_activities_day_id"), ["day_id"], unique=False
        )

    op.create_table(
        "location_points",
        sa.Column("session_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("trip_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("member_id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("accuracy_m", sa.Float(), nullable=True),
        sa.Column("is_approximate", sa.Boolean(), nullable=False),
        sa.Column("recorded_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", yatraai.db.base.TZDateTime(timezone=True), nullable=False),
        sa.Column("id", yatraai.db.base.GUID(length=36), nullable=False),
        sa.CheckConstraint(
            "lat BETWEEN -90 AND 90", name=op.f("ck_location_points_point_lat_range")
        ),
        sa.CheckConstraint(
            "lon BETWEEN -180 AND 180", name=op.f("ck_location_points_point_lon_range")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["location_sharing_sessions.id"],
            name=op.f("fk_location_points_session_id_location_sharing_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_location_points")),
    )
    with op.batch_alter_table("location_points", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_location_points_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_location_points_recorded_at"), ["recorded_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_location_points_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_location_points_trip_id"), ["trip_id"], unique=False)
        batch_op.create_index("ix_locpoint_trip_recorded", ["trip_id", "recorded_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("location_points", schema=None) as batch_op:
        batch_op.drop_index("ix_locpoint_trip_recorded")
        batch_op.drop_index(batch_op.f("ix_location_points_trip_id"))
        batch_op.drop_index(batch_op.f("ix_location_points_session_id"))
        batch_op.drop_index(batch_op.f("ix_location_points_recorded_at"))
        batch_op.drop_index(batch_op.f("ix_location_points_expires_at"))

    op.drop_table("location_points")
    with op.batch_alter_table("itinerary_activities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_itinerary_activities_day_id"))

    op.drop_table("itinerary_activities")
    with op.batch_alter_table("votes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_votes_trip_id"))
        batch_op.drop_index("ix_votes_subject")

    op.drop_table("votes")
    with op.batch_alter_table("sos_alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sos_alerts_trip_id"))

    op.drop_table("sos_alerts")
    with op.batch_alter_table("recommendation_scores", schema=None) as batch_op:
        batch_op.drop_index("ix_recscore_trip_rank")
        batch_op.drop_index(batch_op.f("ix_recommendation_scores_trip_id"))

    op.drop_table("recommendation_scores")
    with op.batch_alter_table("member_preferences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_member_preferences_trip_id"))

    op.drop_table("member_preferences")
    with op.batch_alter_table("location_sharing_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_locsession_trip_status")
        batch_op.drop_index(batch_op.f("ix_location_sharing_sessions_trip_id"))
        batch_op.drop_index(batch_op.f("ix_location_sharing_sessions_member_id"))
        batch_op.drop_index(batch_op.f("ix_location_sharing_sessions_expires_at"))

    op.drop_table("location_sharing_sessions")
    with op.batch_alter_table("itinerary_days", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_itinerary_days_itinerary_id"))

    op.drop_table("itinerary_days")
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feedback_trip_id"))

    op.drop_table("feedback")
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_index("ix_chat_trip_created")
        batch_op.drop_index(batch_op.f("ix_chat_messages_trip_id"))

    op.drop_table("chat_messages")
    with op.batch_alter_table("change_proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_change_proposals_trip_id"))

    op.drop_table("change_proposals")
    with op.batch_alter_table("trip_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trip_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_trip_members_trip_id"))

    op.drop_table("trip_members")
    with op.batch_alter_table("itineraries", schema=None) as batch_op:
        batch_op.drop_index("ix_itineraries_trip_status")
        batch_op.drop_index(batch_op.f("ix_itineraries_trip_id"))

    op.drop_table("itineraries")
    op.drop_table("chunk_embeddings")
    with op.batch_alter_table("attraction_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attraction_sources_attraction_id"))

    op.drop_table("attraction_sources")
    with op.batch_alter_table("attraction_schedules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attraction_schedules_attraction_id"))

    op.drop_table("attraction_schedules")
    with op.batch_alter_table("attraction_costs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attraction_costs_attraction_id"))

    op.drop_table("attraction_costs")
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.drop_index("ix_trips_owner_status")
        batch_op.drop_index(batch_op.f("ix_trips_owner_id"))
        batch_op.drop_index(batch_op.f("ix_trips_invite_code"))
        batch_op.drop_index(batch_op.f("ix_trips_cluster_id"))

    op.drop_table("trips")
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_chunks_document_id"))
        batch_op.drop_index(batch_op.f("ix_document_chunks_content_hash"))
        batch_op.drop_index(batch_op.f("ix_document_chunks_content_category"))
        batch_op.drop_index(batch_op.f("ix_document_chunks_cluster_slug"))
        batch_op.drop_index(batch_op.f("ix_document_chunks_attraction_slug"))
        batch_op.drop_index("ix_chunk_filter")

    op.drop_table("document_chunks")
    with op.batch_alter_table("attractions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attractions_slug"))
        batch_op.drop_index("ix_attractions_geo")
        batch_op.drop_index("ix_attractions_cluster_active")

    op.drop_table("attractions")
    with op.batch_alter_table("weather_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_weather_snapshots_cluster_slug"))

    op.drop_table("weather_snapshots")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.drop_index("ix_srcdoc_cluster_attr")
        batch_op.drop_index(batch_op.f("ix_source_documents_doc_key"))
        batch_op.drop_index(batch_op.f("ix_source_documents_content_hash"))
        batch_op.drop_index(batch_op.f("ix_source_documents_cluster_slug"))
        batch_op.drop_index(batch_op.f("ix_source_documents_attraction_slug"))

    op.drop_table("source_documents")
    with op.batch_alter_table("service_call_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_svc_service_created")
        batch_op.drop_index(batch_op.f("ix_service_call_logs_service"))
        batch_op.drop_index(batch_op.f("ix_service_call_logs_created_at"))

    op.drop_table("service_call_logs")
    with op.batch_alter_table("route_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_route_cache_cache_key"))

    op.drop_table("route_cache")
    with op.batch_alter_table("rag_evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rag_evaluations_run_id"))

    op.drop_table("rag_evaluations")
    with op.batch_alter_table("pipeline_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pipeline_runs_pipeline"))

    op.drop_table("pipeline_runs")
    with op.batch_alter_table("model_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_runs_run_id"))

    op.drop_table("model_runs")
    with op.batch_alter_table("destination_clusters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_destination_clusters_slug"))

    op.drop_table("destination_clusters")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_trip_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))
        batch_op.drop_index("ix_audit_action_created")

    op.drop_table("audit_logs")
    with op.batch_alter_table("analytics_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analytics_events_trip_id"))
        batch_op.drop_index(batch_op.f("ix_analytics_events_event"))
        batch_op.drop_index(batch_op.f("ix_analytics_events_cluster_slug"))

    op.drop_table("analytics_events")
    # ### end Alembic commands ###
